#!/usr/bin/env node

const prog = require('caporal');
const pkgJSON = require('./package.json');
const readConf = require('./src/readConf');
const main = require('./src');

prog
  .version(pkgJSON.version)
  .command('mysql', 'todo...')
  // .argument('<app>', 'App to deploy', /^myapp|their-app$/)
  // .argument('[env]', 'Environment to deploy on', /^dev|staging|production$/, 'local')
  // you specify options using .option()
  // if --tail is passed, its value is required
  // .option('--tail <lines>', 'Tail <lines> lines of logs after deploy', prog.INT)
  .action(function(args, options, logger) {
    const conf = readConf(logger);
		console.log(conf.searchPaths);
    main(conf.searchPaths).then(answers => {
      console.log('answers:');
      console.log(answers)
    });
  });

prog.parse(process.argv);
